# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
pip install gmaps

Requirement already satisfied: gmaps in c:\users\trish\anaconda3\envs\pythondata\lib\site-packages (0.9.0)
Requirement already satisfied: ipywidgets>=7.0.0 in c:\users\trish\anaconda3\envs\pythondata\lib\site-packages (from gmaps) (7.6.5)
Requirement already satisfied: traitlets>=4.3.0 in c:\users\trish\anaconda3\envs\pythondata\lib\site-packages (from gmaps) (5.1.1)
Requirement already satisfied: six in c:\users\trish\anaconda3\envs\pythondata\lib\site-packages (from gmaps) (1.15.0)
Requirement already satisfied: geojson>=2.0.0 in c:\users\trish\anaconda3\envs\pythondata\lib\site-packages (from gmaps) (2.5.0)
Requirement already satisfied: ipython>=5.3.0 in c:\users\trish\anaconda3\envs\pythondata\lib\site-packages (from gmaps) (7.31.1)
Requirement already satisfied: nbformat>=4.2.0 in c:\users\trish\anaconda3\envs\pythondata\lib\site-packages (from ipywidgets>=7.0.0->gmaps) (5.1.3)
Requirement already satisfied: ipykernel>=4.5.1 in c:\users\trish\anaconda3\envs\pythondata\lib\site-packages (from ipywidgets>=7.0.0->gmaps) (6.9.1)
Requirement already satisfied: widgetsnbextension~=3.5.0 in c:\users\trish\anaconda3\envs\pythondata\lib\site-packages (from ipywidgets>=7.0.0->gmaps) (3.5.2)
Requirement already satisfied: ipython-genutils~=0.2.0 in c:\users\trish\anaconda3\envs\pythondata\lib\site-packages (from ipywidgets>=7.0.0->gmaps) (0.2.0)
Requirement already satisfied: jupyterlab-widgets>=1.0.0; python_version >= "3.6" in c:\users\trish\anaconda3\envs\pythondata\lib\site-packages (from ipywidgets>=7.0.0->gmaps) (1.0.0)
Requirement already satisfied: backcall in c:\users\trish\anaconda3\envs\pythondata\lib\site-packages (from ipython>=5.3.0->gmaps) (0.2.0)
Requirement already satisfied: decorator in c:\users\trish\anaconda3\envs\pythondata\lib\site-packages (from ipython>=5.3.0->gmaps) (5.1.1)
Requirement already satisfied: jedi>=0.16 in c:\users\trish\anaconda3\envs\pythondata\lib\site-packages (from ipython>=5.3.0->gmaps) (0.18.1)
Requirement already satisfied: pygments in c:\users\trish\anaconda3\envs\pythondata\lib\site-packages (from ipython>=5.3.0->gmaps) (2.11.2)
Requirement already satisfied: colorama; sys_platform == "win32" in c:\users\trish\anaconda3\envs\pythondata\lib\site-packages (from ipython>=5.3.0->gmaps) (0.4.4)
Requirement already satisfied: matplotlib-inline in c:\users\trish\anaconda3\envs\pythondata\lib\site-packages (from ipython>=5.3.0->gmaps) (0.1.2)
Requirement already satisfied: setuptools>=18.5 in c:\users\trish\anaconda3\envs\pythondata\lib\site-packages (from ipython>=5.3.0->gmaps) (47.3.1.post20200622)
Requirement already satisfied: pickleshare in c:\users\trish\anaconda3\envs\pythondata\lib\site-packages (from ipython>=5.3.0->gmaps) (0.7.5)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in c:\users\trish\anaconda3\envs\pythondata\lib\site-packages (from ipython>=5.3.0->gmaps) (3.0.20)
Requirement already satisfied: jupyter-core in c:\users\trish\anaconda3\envs\pythondata\lib\site-packages (from nbformat>=4.2.0->ipywidgets>=7.0.0->gmaps) (4.9.2)
Requirement already satisfied: jsonschema!=2.5.0,>=2.4 in c:\users\trish\anaconda3\envs\pythondata\lib\site-packages (from nbformat>=4.2.0->ipywidgets>=7.0.0->gmaps) (3.2.0)
Requirement already satisfied: jupyter-client<8.0 in c:\users\trish\anaconda3\envs\pythondata\lib\site-packages (from ipykernel>=4.5.1->ipywidgets>=7.0.0->gmaps) (7.1.2)
Requirement already satisfied: tornado<7.0,>=4.2 in c:\users\trish\anaconda3\envs\pythondata\lib\site-packages (from ipykernel>=4.5.1->ipywidgets>=7.0.0->gmaps) (6.0.4)
Requirement already satisfied: debugpy<2.0,>=1.0.0 in c:\users\trish\anaconda3\envs\pythondata\lib\site-packages (from ipykernel>=4.5.1->ipywidgets>=7.0.0->gmaps) (1.5.1)
Requirement already satisfied: nest-asyncio in c:\users\trish\anaconda3\envs\pythondata\lib\site-packages (from ipykernel>=4.5.1->ipywidgets>=7.0.0->gmaps) (1.5.1)
Requirement already satisfied: notebook>=4.4.1 in c:\users\trish\anaconda3\envs\pythondata\lib\site-packages (from widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (5.7.10)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in c:\users\trish\anaconda3\envs\pythondata\lib\site-packages (from jedi>=0.16->ipython>=5.3.0->gmaps) (0.8.3)
Requirement already satisfied: wcwidth in c:\users\trish\anaconda3\envs\pythondata\lib\site-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=5.3.0->gmaps) (0.2.5)
Requirement already satisfied: pywin32>=1.0; sys_platform == "win32" and platform_python_implementation != "PyPy" in c:\users\trish\anaconda3\envs\pythondata\lib\site-packages (from jupyter-core->nbformat>=4.2.0->ipywidgets>=7.0.0->gmaps) (227)
Requirement already satisfied: pyrsistent>=0.14.0 in c:\users\trish\anaconda3\envs\pythondata\lib\site-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.2.0->ipywidgets>=7.0.0->gmaps) (0.18.0)
Requirement already satisfied: attrs>=17.4.0 in c:\users\trish\anaconda3\envs\pythondata\lib\site-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.2.0->ipywidgets>=7.0.0->gmaps) (21.4.0)
Requirement already satisfied: importlib-metadata; python_version < "3.8" in c:\users\trish\anaconda3\envs\pythondata\lib\site-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.2.0->ipywidgets>=7.0.0->gmaps) (4.11.3)
Requirement already satisfied: python-dateutil>=2.1 in c:\users\trish\anaconda3\envs\pythondata\lib\site-packages (from jupyter-client<8.0->ipykernel>=4.5.1->ipywidgets>=7.0.0->gmaps) (2.8.1)
Requirement already satisfied: pyzmq>=13 in c:\users\trish\anaconda3\envs\pythondata\lib\site-packages (from jupyter-client<8.0->ipykernel>=4.5.1->ipywidgets>=7.0.0->gmaps) (22.3.0)
Requirement already satisfied: entrypoints in c:\users\trish\anaconda3\envs\pythondata\lib\site-packages (from jupyter-client<8.0->ipykernel>=4.5.1->ipywidgets>=7.0.0->gmaps) (0.3)
Requirement already satisfied: nbconvert<6.0 in c:\users\trish\anaconda3\envs\pythondata\lib\site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (5.5.0)
Requirement already satisfied: terminado>=0.8.1 in c:\users\trish\anaconda3\envs\pythondata\lib\site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (0.9.4)
Requirement already satisfied: jinja2 in c:\users\trish\anaconda3\envs\pythondata\lib\site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (3.0.3)
Requirement already satisfied: prometheus-client in c:\users\trish\anaconda3\envs\pythondata\lib\site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (0.13.1)
Requirement already satisfied: Send2Trash in c:\users\trish\anaconda3\envs\pythondata\lib\site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (1.8.0)
Requirement already satisfied: typing-extensions>=3.6.4; python_version < "3.8" in c:\users\trish\anaconda3\envs\pythondata\lib\site-packages (from importlib-metadata; python_version < "3.8"->jsonschema!=2.5.0,>=2.4->nbformat>=4.2.0->ipywidgets>=7.0.0->gmaps) (4.1.1)
Requirement already satisfied: zipp>=0.5 in c:\users\trish\anaconda3\envs\pythondata\lib\site-packages (from importlib-metadata; python_version < "3.8"->jsonschema!=2.5.0,>=2.4->nbformat>=4.2.0->ipywidgets>=7.0.0->gmaps) (3.7.0)
Requirement already satisfied: bleach in c:\users\trish\anaconda3\envs\pythondata\lib\site-packages (from nbconvert<6.0->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (4.1.0)
Requirement already satisfied: testpath in c:\users\trish\anaconda3\envs\pythondata\lib\site-packages (from nbconvert<6.0->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (0.5.0)
Requirement already satisfied: defusedxml in c:\users\trish\anaconda3\envs\pythondata\lib\site-packages (from nbconvert<6.0->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (0.7.1)
Requirement already satisfied: pandocfilters>=1.4.1 in c:\users\trish\anaconda3\envs\pythondata\lib\site-packages (from nbconvert<6.0->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (1.5.0)
Requirement already satisfied: mistune>=0.8.1 in c:\users\trish\anaconda3\envs\pythondata\lib\site-packages (from nbconvert<6.0->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (0.8.4)
Requirement already satisfied: pywinpty>=0.5 in c:\users\trish\anaconda3\envs\pythondata\lib\site-packages (from terminado>=0.8.1->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (0.5.7)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\trish\anaconda3\envs\pythondata\lib\site-packages (from jinja2->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (2.0.1)
Requirement already satisfied: packaging in c:\users\trish\anaconda3\envs\pythondata\lib\site-packages (from bleach->nbconvert<6.0->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (21.3)
Requirement already satisfied: webencodings in c:\users\trish\anaconda3\envs\pythondata\lib\site-packages (from bleach->nbconvert<6.0->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (0.5.1)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in c:\users\trish\anaconda3\envs\pythondata\lib\site-packages (from packaging->bleach->nbconvert<6.0->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (2.4.7)
Note: you may need to restart the kernel to use updated packages.

In [2]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os
import json

# Import API key
from api_keys import g_key

In [3]:
#print(g_key)

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [6]:
#filepath
file = "../output_data/cities.csv"

#read the csv and create a dataframe
cities_data = pd.DataFrame(pd.read_csv(file, index_col="City ID"))

#display the dataframe 
cities_data

,City,Country,Date,Lat,Lng,Max Temp (F),Humidity (%),Cloudiness (%),Wind Speed (mph)
City ID,,,,,,,,,
0,Santa Rosalía,MX,2022-10-24 14:19:34,27.3167,-112.2833,63.68,75,3,9.89
1,Kieta,PG,2022-10-24 14:19:35,-6.2167,155.6333,79.56,84,65,0.27
2,Kavieng,PG,2022-10-24 14:19:35,-2.5744,150.7967,82.17,74,59,5.46
3,Mar del Plata,AR,2022-10-24 14:19:36,-38.0023,-57.5575,69.82,75,40,18.01
4,Ushuaia,AR,2022-10-24 14:19:36,-54.8000,-68.3000,46.02,65,75,11.50
...,...,...,...,...,...,...,...,...,...
547,Charters Towers,AU,2022-10-24 14:24:02,-20.1000,146.2667,77.22,77,28,12.59
548,Goba,ET,2022-10-24 14:24:03,7.0167,39.9833,56.14,87,80,2.91
549,Hargeisa,SO,2022-10-24 14:24:03,9.5600,44.0650,77.16,54,84,14.14
550,Krasnogorodskoye,RU,2022-10-24 14:24:05,56.8357,28.2822,44.22,74,51,0.56
551,Haverfordwest,GB,2022-10-24 14:24:06,51.8017,-4.9691,62.58,84,51,8.01

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [8]:
# unique API key for google maps
gmaps.configure(api_key=g_key)

In [9]:
#Lat and Lng as locations and Humidity as the weight
locations = cities_data[["Lat", "Lng"]]
weights = cities_data["Humidity (%)"]

In [10]:
#Add heatmap layer to map
figure_layout = {
    'width': "100%",
    'height': '400px',
#    'border': '1px solid black',
    'padding': '1px',
#    'margin': '0 auto 0 auto'
}
fig = gmaps.figure(layout=figure_layout, center=(20.0, 5.0), zoom_level=1.9)
heatmap_layer = gmaps.heatmap_layer(locations, weights=weights, dissipating=False)
fig.add_layer(heatmap_layer)

#Set maximum intensity and point_radius setting
heatmap_layer.max_intensity = max(weights)
heatmap_layer.point_radius = 3

#Display heatmap
fig

Figure(layout=FigureLayout(height='400px', padding='1px', width='100%'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [11]:
#Create dataframe with conditional statements to fit the below criteria
# 1. A max temperature lower than 80 degrees but higher than 70.
# 2. Wind speed less than 10 mph.
# 3. Zero cloudiness.
# 4. Humidity is less than 75%

ideal_cities = cities_data.loc[(cities_data["Max Temp (F)"] > 70) & 
                               (cities_data["Max Temp (F)"] < 80) & 
                               (cities_data["Wind Speed (mph)"] < 10) & 
                               (cities_data["Cloudiness (%)"] == 0) &
                               (cities_data["Humidity (%)"] < 75), :].reset_index(drop=True).dropna()
ideal_cities

,City,Country,Date,Lat,Lng,Max Temp (F),Humidity (%),Cloudiness (%),Wind Speed (mph)
0,Athani,IN,2022-10-24 14:16:36,16.7333,75.0667,73.13,54,0,6.42
1,Kerman,IR,2022-10-24 14:21:03,30.2832,57.0788,73.26,14,0,4.61
2,Alexandria,EG,2022-10-24 14:22:45,31.2156,29.9553,72.54,50,0,9.71
3,Kot Addu,PK,2022-10-24 14:19:18,30.4692,70.9671,78.21,26,0,4.99
4,Sikandra,IN,2022-10-24 14:21:51,26.3667,79.6500,74.97,45,0,5.61
5,Waddān,LY,2022-10-24 14:21:57,29.1614,16.1390,79.54,24,0,5.26
6,Ribeirão Branco,BR,2022-10-24 14:22:05,-24.2208,-48.7656,74.52,51,0,4.56
7,Santa Maria,BR,2022-10-24 14:22:14,-29.6842,-53.8069,70.39,53,0,8.55
8,Berasia,IN,2022-10-24 14:22:27,23.6333,77.4333,73.85,45,0,5.61
9,Erzin,TR,2022-10-24 14:23:09,36.9559,36.2000,75.70,33,0,1.86
10,Dhār,IN,2022-10-24 14:23:19,22.6000,75.3000,71.37,39,0,5.88
11,Idlib,SY,2022-10-24 14:23:28,35.9306,36.6339,76.86,31,0,1.54
12,Lakshettipet,IN,2022-10-24 14:23:58,18.8667,79.2167,70.84,67,0,3.87
13,Salto,UY,2022-10-24 14:23:59,-31.3833,-57.9667,73.56,53,0,9.22

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [17]:
ideal_cities['Hotel Name'] = ''
ideal_cities

,City,Country,Date,Lat,Lng,Max Temp (F),Humidity (%),Cloudiness (%),Wind Speed (mph),Hotel Name
0,Athani,IN,2022-10-24 14:16:36,16.7333,75.0667,73.13,54,0,6.42,
1,Kerman,IR,2022-10-24 14:21:03,30.2832,57.0788,73.26,14,0,4.61,
2,Alexandria,EG,2022-10-24 14:22:45,31.2156,29.9553,72.54,50,0,9.71,
3,Kot Addu,PK,2022-10-24 14:19:18,30.4692,70.9671,78.21,26,0,4.99,
4,Sikandra,IN,2022-10-24 14:21:51,26.3667,79.6500,74.97,45,0,5.61,
5,Waddān,LY,2022-10-24 14:21:57,29.1614,16.1390,79.54,24,0,5.26,
6,Ribeirão Branco,BR,2022-10-24 14:22:05,-24.2208,-48.7656,74.52,51,0,4.56,
7,Santa Maria,BR,2022-10-24 14:22:14,-29.6842,-53.8069,70.39,53,0,8.55,
8,Berasia,IN,2022-10-24 14:22:27,23.6333,77.4333,73.85,45,0,5.61,
9,Erzin,TR,2022-10-24 14:23:09,36.9559,36.2000,75.70,33,0,1.86,
10,Dhār,IN,2022-10-24 14:23:19,22.6000,75.3000,71.37,39,0,5.88,
11,Idlib,SY,2022-10-24 14:23:28,35.9306,36.6339,76.86,31,0,1.54,
12,Lakshettipet,IN,2022-10-24 14:23:58,18.8667,79.2167,70.84,67,0,3.87,
13,Salto,UY,2022-10-24 14:23:59,-31.3833,-57.9667,73.56,53,0,9.22,

In [19]:
hotel_df = []
base_url = 'https://maps.googleapis.com/maps/api/place/nearbysearch/json?'
params = {
    "rankby": "distance",
    "type": "lodging",
    "key": g_key,
}
target_radius = 5000
for index, row in ideal_cities.iterrows():
    try:
        params['location'] = f'{row[1]},{row[2]}'
        response = requests.get(base_url, params=params).json()
        # extract results
        results = response['results']
        hotel_df.append(results[0]['name'])
    except IndexError:
        print(f'No hotel within 5000 m of {row[0]}')
        hotel_df.append('n/a')
ideal_cities['Hotel Name'] = hotel_df
ideal_cities

No hotel within 5000 m of Athani
No hotel within 5000 m of Kerman
No hotel within 5000 m of Alexandria
No hotel within 5000 m of Kot Addu
No hotel within 5000 m of Sikandra
No hotel within 5000 m of Waddān
No hotel within 5000 m of Ribeirão Branco
No hotel within 5000 m of Santa Maria
No hotel within 5000 m of Berasia
No hotel within 5000 m of Erzin
No hotel within 5000 m of Dhār
No hotel within 5000 m of Idlib
No hotel within 5000 m of Lakshettipet
No hotel within 5000 m of Salto

,City,Country,Date,Lat,Lng,Max Temp (F),Humidity (%),Cloudiness (%),Wind Speed (mph),Hotel Name
0,Athani,IN,2022-10-24 14:16:36,16.7333,75.0667,73.13,54,0,6.42,n/a
1,Kerman,IR,2022-10-24 14:21:03,30.2832,57.0788,73.26,14,0,4.61,n/a
2,Alexandria,EG,2022-10-24 14:22:45,31.2156,29.9553,72.54,50,0,9.71,n/a
3,Kot Addu,PK,2022-10-24 14:19:18,30.4692,70.9671,78.21,26,0,4.99,n/a
4,Sikandra,IN,2022-10-24 14:21:51,26.3667,79.6500,74.97,45,0,5.61,n/a
5,Waddān,LY,2022-10-24 14:21:57,29.1614,16.1390,79.54,24,0,5.26,n/a
6,Ribeirão Branco,BR,2022-10-24 14:22:05,-24.2208,-48.7656,74.52,51,0,4.56,n/a
7,Santa Maria,BR,2022-10-24 14:22:14,-29.6842,-53.8069,70.39,53,0,8.55,n/a
8,Berasia,IN,2022-10-24 14:22:27,23.6333,77.4333,73.85,45,0,5.61,n/a
9,Erzin,TR,2022-10-24 14:23:09,36.9559,36.2000,75.70,33,0,1.86,n/a
10,Dhār,IN,2022-10-24 14:23:19,22.6000,75.3000,71.37,39,0,5.88,n/a
11,Idlib,SY,2022-10-24 14:23:28,35.9306,36.6339,76.86,31,0,1.54,n/a
12,Lakshettipet,IN,2022-10-24 14:23:58,18.8667,79.2167,70.84,67,0,3.87,n/a
13,Salto,UY,2022-10-24 14:23:59,-31.3833,-57.9667,73.56,53,0,9.22,n/a

In [23]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in ideal_cities.iterrows()]
locations = ideal_cities[["Lat", "Lng"]]

In [24]:
# Add marker layer ontop of heat map
markers = gmaps.marker_layer(locations, info_box_content = hotel_info)
fig.add_layer(markers)

# Display figure
fig

Figure(layout=FigureLayout(height='400px', padding='1px', width='100%'))